language: objective-c
osx_image: xcode7.1
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=9.1,name=iPhone 6s" SDK=iphonesimulator9.1
    - DESTINATION="OS=9.0,name=iPhone 6 Plus" SDK=iphonesimulator9.1
    - DESTINATION="OS=8.4,name=iPhone 6" SDK=iphonesimulator9.1
    - DESTINATION="OS=8.3,name=iPhone 5S" SDK=iphonesimulator9.1
    - DESTINATION="OS=8.2,name=iPhone 5" SDK=iphonesimulator9.1
    - DESTINATION="OS=8.1,name=iPhone 4S" SDK=iphonesimulator9.1
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - cd Tests && pod install && cd $TRAVIS_BUILD_DIR
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace src/Nimbus.xcodeproj/project.xcworkspace -scheme NimbusCore -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c; 
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick;
    fi
